Repository docsifyjs/docsify, pull requests merged in 2020-06, with the labels that each got.

#1188 style: Get emoji from github api
  index.html
  src/plugins/emoji.js
Labels: enhancement, semver-minor

#1189 Allow configs to be functions
  .editorconfig
  build/build.js
  build/css.js
  build/mincss.js
  build/ssr.js
  docs/configuration.md
  package-lock.json
  package.json
  src/core/Docsify.js
  src/core/config.js
  src/core/global-api.js
  src/core/index.js
  src/core/init/index.js
  src/core/util/dom.js
  test/_helper.js
  test/unit/docsify.test.js
Labels: semver-minor

#1128 update: added html sanitizer for remote rendering
  .eslintrc.js
  package-lock.json
  package.json
  packages/docsify-server-renderer/index.js
  packages/docsify-server-renderer/package-lock.json
  packages/docsify-server-renderer/package.json
  src/core/fetch/index.js
  src/core/render/index.js
Labels: semver-patch

#1251 Update language-highlight.md
  docs/language-highlight.md
Labels: docs
